title:            computerclub.io
description:      Austin, New York City, San Francisco
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://computerclub.io
    external:     true
  - name:         Email
    url:          mailto:Ahoyhoy@computerclub.io
    external:     true
  - name:         GitHub
    url:          http://github.com/computerclub.io
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
